config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root to: 'pages#home'
  get 'pages/home'
  resources :equivalences
  resources :classroom_students
  resources :subject_courses
  resources :lession_students
  resources :periods
  resources :classrooms
  resources :lessions
  resources :students
  resources :teachers
  resources :subjects
  resources :courses
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
     
      elsif user.kind== "coordenator"
        can :manage, [Department,Teacher,Course,Student,Period,Classroom,Lession,Subject]
        
        can :update, user
      elsif user.kind==  "standard"
        can :read, :all
        can :update, user    
      end

      
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  belongs_to :subject
  belongs_to :period
  has_many :classroom_students
  has_many :students, :through => :classroom_students
end

app/models/classroom_student.rb
class ClassroomStudent < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :students
  has_many :subject_courses
  has_many :subject, :through => :subject_courses
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :courses
    has_many :subjects
    has_many :teachers
end

app/models/equivalence.rb
class Equivalence < ApplicationRecord
  belongs_to :discipline, class_name: "Subject"
  belongs_to :subject
end

app/models/lession.rb
class Lession < ApplicationRecord
  belongs_to :classroom
  has_many :lession_students
  has_many :students, :through =>:lession_student
end

app/models/lession_student.rb
class LessionStudent < ApplicationRecord
  belongs_to :lession
  belongs_to :student
end

app/models/period.rb
class Period < ApplicationRecord
    has_many :classrooms
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :classroom_students
  has_many :lession_students
  has_many :classrooms, :through => :classroom_students
  has_many :lessions, :through => :lession_students
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department
  has_many :classrooms
  has_many :subject_courses
  has_many :equivalences
  has_many :courses, through: :subject_courses
  has_many :disciplines, :through => :equivalences,:source => :discipline
end

app/models/subject_course.rb
class SubjectCourse < ApplicationRecord
  belongs_to :subject
  belongs_to :course
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
  belongs_to :user
  has_many :classrooms

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_one :teacher
    mount_uploader :avatar, AvatarUploader
    enum kind: {
      standard: 2,
      admin: 1,
      coordenator: 3
    }
end

app/controllers/lessions_controller.rb
class LessionsController < ApplicationController
  before_action :set_lession, only: [:show, :edit, :update, :destroy]

  # GET /lessions
  # GET /lessions.json
  def index
    @lessions = Lession.all
  end

  # GET /lessions/1
  # GET /lessions/1.json
  def show
  end

  # GET /lessions/new
  def new
    @lession = Lession.new
    @classrooms = Classroom.all
  end

  # GET /lessions/1/edit
  def edit
    @classrooms = Classroom.all
  end

  # POST /lessions
  # POST /lessions.json
  def create
    @lession = Lession.new(lession_params)

    respond_to do |format|
      if @lession.save
        format.html { redirect_to @lession, notice: 'Lession was successfully created.' }
        format.json { render :show, status: :created, location: @lession }
      else
        format.html { render :new }
        format.json { render json: @lession.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessions/1
  # PATCH/PUT /lessions/1.json
  def update
    respond_to do |format|
      if @lession.update(lession_params)
        format.html { redirect_to @lession, notice: 'Lession was successfully updated.' }
        format.json { render :show, status: :ok, location: @lession }
      else
        format.html { render :edit }
        format.json { render json: @lession.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessions/1
  # DELETE /lessions/1.json
  def destroy
    @lession.destroy
    respond_to do |format|
      format.html { redirect_to lessions_url, notice: 'Lession was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lession
      @lession = Lession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lession_params
      params.require(:lession).permit(:lession_date, :lession_time, :classroom_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessions_helper.rb
module LessionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
   
end

app/helpers/users_helper.rb
module UsersHelper
    def user_kind_option
        [["padrao", :standard]]
    end

    def user_kind_option_with_admin
        [["padrao", :standard],["coordenador", :coordenator],["adimistrador", :admin]]
    end
    

end

app/views/lessions/_form.html.erb
<%= form_with(model: lession, local: true) do |form| %>
  <% if lession.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lession.errors.count, "error") %> prohibited this lession from being saved:</h2>

      <ul>
      <% lession.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lession_date %>
    <%= form.date_select :lession_date %>
  </div>

  <div class="field">
    <%= form.label :lession_time %>
    <%= form.time_select :lession_time %>
  </div>

  <div class="field">
    <%= form.label :classroom_id %>
    <%= form.select :classroom_id, @classrooms.collect { |classroom| [classroom.registration, classroom.id]}%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lessions/edit.html.erb
<h1>Editing Lession</h1>

<%= render 'form', lession: @lession %>

<%= link_to 'ver mais sobre', @lession %> |
<%= link_to  'voltar', lessions_path %>

app/views/lessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aula</h1>

<table>
  <thead>
    <tr>
      <th>Dia</th>
      <th>Horario</th>
      <th>Turma</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessions.each do |lession| %>
      <tr>
        <td><%=l lession.lession_date %></td>
        <td><%=l lession.lession_time %></td>
        <td><%= lession.classroom.registration  %></td>
        <td><%= link_to 'ver mais sobre', lession %></td>
        <% if can? :manager, Lession%>
        <td><%= link_to 'Editar', edit_lession_path(lession) %></td>
        <td><%= link_to 'excluir', lession, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :manager, Lession%>
  <%= link_to 'Nova Aula', new_lession_path %>
<% end %>

app/views/lessions/new.html.erb
<h1>New Lession</h1>

<%= render 'form', lession: @lession %>

<%= link_to  'voltar', lessions_path %>

app/views/lessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dia:</strong>
  <%= @lession.lession_date %>
</p>

<p>
  <strong>Horario:</strong>
  <%= @lession.lession_time %>
</p>

<p>
  <strong>Turma:</strong>
  <%= @lession.classroom.registration %>
</p>
<h3>Essa aula terá os seguintes alunos: </h3>
<% for lession_student in @lession.lession_students%>
  <%= Student.find_by(id: lession_student.lession_id).name%>
  <%= link_to  "deletar", lession_student,method: :delete %>
<%end%>
<br/>
<% if can? :manager, @lessions%>
  <%= link_to 'Editar', edit_lession_path(@lession) %> |
<% end %>
<%= link_to  'voltar', lessions_path %>