config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root to: 'pages#home'
  get 'pages/home'
  resources :equivalences
  resources :classroom_students
  resources :subject_courses
  resources :lession_students
  resources :periods
  resources :classrooms
  resources :lessions
  resources :students
  resources :teachers
  resources :subjects
  resources :courses
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
     
      elsif user.kind== "coordenator"
        can :manage, [Department,Teacher,Course,Student,Period,Classroom,Lession,Subject]
        
        can :update, user
      elsif user.kind==  "standard"
        can :read, :all
        can :update, user    
      end

      
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  belongs_to :subject
  belongs_to :period
  has_many :classroom_students
  has_many :students, :through => :classroom_students
end

app/models/classroom_student.rb
class ClassroomStudent < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :students
  has_many :subject_courses
  has_many :subject, :through => :subject_courses
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :courses
    has_many :subjects
    has_many :teachers
end

app/models/equivalence.rb
class Equivalence < ApplicationRecord
  belongs_to :discipline, class_name: "Subject"
  belongs_to :subject
end

app/models/lession.rb
class Lession < ApplicationRecord
  belongs_to :classroom
  has_many :lession_students
  has_many :students, :through =>:lession_student
end

app/models/lession_student.rb
class LessionStudent < ApplicationRecord
  belongs_to :lession
  belongs_to :student
end

app/models/period.rb
class Period < ApplicationRecord
    has_many :classrooms
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :classroom_students
  has_many :lession_students
  has_many :classrooms, :through => :classroom_students
  has_many :lessions, :through => :lession_students
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department
  has_many :classrooms
  has_many :subject_courses
  has_many :equivalences
  has_many :courses, through: :subject_courses
  has_many :disciplines, :through => :equivalences,:source => :discipline
end

app/models/subject_course.rb
class SubjectCourse < ApplicationRecord
  belongs_to :subject
  belongs_to :course
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
  belongs_to :user
  has_many :classrooms

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_one :teacher
    mount_uploader :avatar, AvatarUploader
    enum kind: {
      standard: 2,
      admin: 1,
      coordenator: 3
    }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    @courses = Course.all
  end

  # GET /students/1/edit
  def edit
    @courses = Course.all
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :course_id, :age)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessions_helper.rb
module LessionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
   
end

app/helpers/users_helper.rb
module UsersHelper
    def user_kind_option
        [["padrao", :standard]]
    end

    def user_kind_option_with_admin
        [["padrao", :standard],["coordenador", :coordenator],["adimistrador", :admin]]
    end
    

end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.select :course_id, @courses.collect{ |course| [course.name, course.id]}  %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'ver mais sobre', @student %> |
<%= link_to  'voltar', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aluno</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Curso</th>
      <th>Idade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.course.name %></td>
        <td><%= student.age %></td>
        <td><%= link_to 'ver mais sobre', student %></td>
        <% if can? :manager, Student%>
          <td><%= link_to 'Editar', edit_student_path(student) %></td>
          <td><%= link_to 'excluir', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :manager, Student%>
  <%= link_to 'Novo Estudante', new_student_path %>
  <%= link_to 'Adicionar aula ao alunno', new_lession_student_path%>
<% end %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to  'voltar', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @student.course.name %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @student.age %>
</p>
<h3> As turma desse aluno:</h3>
<% for classroom_student in @student.classroom_students%>
  <%= Classroom.find_by(id: classroom_student.classroom).registration%>
  <%= link_to  "deletar", classroom_student,method: :delete %>
<%end%>
<br/>



<h3>As aulas desse aluno serão:</h3>
<% for lession_student in @student.lession_students%>
  <%=l Lession.find_by(id: lession_student.lession_id).lession_date%>
  <%= link_to  "deletar", lession_student,method: :delete %>
<%end%>
<br>
<% if can? :manager, @student%>
  <%= link_to 'Editar', edit_student_path(@student) %> |
<% end %>
<%= link_to  'voltar', students_path %>