config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root to: 'pages#home'
  get 'pages/home'
  resources :equivalences
  resources :classroom_students
  resources :subject_courses
  resources :lession_students
  resources :periods
  resources :classrooms
  resources :lessions
  resources :students
  resources :teachers
  resources :subjects
  resources :courses
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
     
      elsif user.kind== "coordenator"
        can :manage, [Department,Teacher,Course,Student,Period,Classroom,Lession,Subject]
        
        can :update, user
      elsif user.kind==  "standard"
        can :read, :all
        can :update, user    
      end

      
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  belongs_to :subject
  belongs_to :period
  has_many :classroom_students
  has_many :students, :through => :classroom_students
end

app/models/classroom_student.rb
class ClassroomStudent < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :students
  has_many :subject_courses
  has_many :subject, :through => :subject_courses
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :courses
    has_many :subjects
    has_many :teachers
end

app/models/equivalence.rb
class Equivalence < ApplicationRecord
  belongs_to :discipline, class_name: "Subject"
  belongs_to :subject
end

app/models/lession.rb
class Lession < ApplicationRecord
  belongs_to :classroom
  has_many :lession_students
  has_many :students, :through =>:lession_student
end

app/models/lession_student.rb
class LessionStudent < ApplicationRecord
  belongs_to :lession
  belongs_to :student
end

app/models/period.rb
class Period < ApplicationRecord
    has_many :classrooms
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :classroom_students
  has_many :lession_students
  has_many :classrooms, :through => :classroom_students
  has_many :lessions, :through => :lession_students
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department
  has_many :classrooms
  has_many :subject_courses
  has_many :equivalences
  has_many :courses, through: :subject_courses
  has_many :disciplines, :through => :equivalences,:source => :discipline
end

app/models/subject_course.rb
class SubjectCourse < ApplicationRecord
  belongs_to :subject
  belongs_to :course
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
  belongs_to :user
  has_many :classrooms

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_one :teacher
    mount_uploader :avatar, AvatarUploader
    enum kind: {
      standard: 2,
      admin: 1,
      coordenator: 3
    }
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
    @departments =Department.all
  end

  # GET /subjects/1/edit
  def edit
    @departments =Department.all
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :registration, :department_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessions_helper.rb
module LessionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
   
end

app/helpers/users_helper.rb
module UsersHelper
    def user_kind_option
        [["padrao", :standard]]
    end

    def user_kind_option_with_admin
        [["padrao", :standard],["coordenador", :coordenator],["adimistrador", :admin]]
    end
    

end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :registration %>
    <%= form.text_field :registration %>
  </div>

  <div class="field">
    <%= form.label :department_id %>
    <%= form.select :department_id, @departments.collect { |department| [department.name, department.id]}%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'ver mais sobre', @subject %> |
<%= link_to  'voltar', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Disciplina</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Registro</th>
      <th>Departamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.registration %></td>
        <td><%= subject.department.name %></td>
        <td><%= link_to 'ver mais sobre', subject %></td>
        <% if can? :manager,Subject%>
          <td><%= link_to 'Editar', edit_subject_path(subject) %></td>
          <td><%= link_to 'excluir', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :manager,Subject%>
  <%= link_to 'Nova Disciplina', new_subject_path %>
  <%=link_to 'Nova materia equivalente', new_equivalence_path%>
<%end%>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to  'voltar', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Registro:</strong>
  <%= @subject.registration %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @subject.department.name %>
</p>

<h3>Turmas </h3>
<% for classroom in @subject.classrooms%>
  <p><%= classroom.registration%></p>
<%end%>

<h3>Essa materia tem nos cursos: </h3>
<% for subject_course in @subject.subject_courses%>
  <%= Course.find_by(id: subject_course.course_id).name%>
  <%= link_to  "deletar", subject_course,method: :delete %>
  <br>
<%end%>
<br/>


<h3>Esssa materia é equivalente a: </h3>

<% for equivalence in Equivalence.where(subject_id: @subject.id) %>
  <div>
    <% aux=Subject.find_by(id: equivalence.discipline_id)%>
    <%= aux.name%>
    <%= link_to  "deletar", equivalence,method: :delete %>
  </div>
<% end %>

<% for equivalence in Equivalence.where(discipline_id: @subject.id) %>
  <div>
    <% aux=Subject.find_by(id: equivalence.subject_id)%>
    <%= aux.name%>
    <%= link_to  "deletar", equivalence,method: :delete %>
  </div>
<% end %>


<% if can? :manage, @subject%>
  <%= link_to 'Editar', edit_subject_path(@subject) %> |
<% end %>
<%= link_to  'voltar', subjects_path %>