config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  root to: 'pages#home'
  get 'pages/home'
  resources :equivalences
  resources :classroom_students
  resources :subject_courses
  resources :lession_students
  resources :periods
  resources :classrooms
  resources :lessions
  resources :students
  resources :teachers
  resources :subjects
  resources :courses
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
     
      elsif user.kind== "coordenator"
        can :manage, [Department,Teacher,Course,Student,Period,Classroom,Lession,Subject]
        
        can :update, user
      elsif user.kind==  "standard"
        can :read, :all
        can :update, user    
      end

      
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  belongs_to :subject
  belongs_to :period
  has_many :classroom_students
  has_many :students, :through => :classroom_students
end

app/models/classroom_student.rb
class ClassroomStudent < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :students
  has_many :subject_courses
  has_many :subject, :through => :subject_courses
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :courses
    has_many :subjects
    has_many :teachers
end

app/models/equivalence.rb
class Equivalence < ApplicationRecord
  belongs_to :discipline, class_name: "Subject"
  belongs_to :subject
end

app/models/lession.rb
class Lession < ApplicationRecord
  belongs_to :classroom
  has_many :lession_students
  has_many :students, :through =>:lession_student
end

app/models/lession_student.rb
class LessionStudent < ApplicationRecord
  belongs_to :lession
  belongs_to :student
end

app/models/period.rb
class Period < ApplicationRecord
    has_many :classrooms
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :classroom_students
  has_many :lession_students
  has_many :classrooms, :through => :classroom_students
  has_many :lessions, :through => :lession_students
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department
  has_many :classrooms
  has_many :subject_courses
  has_many :equivalences
  has_many :courses, through: :subject_courses
  has_many :disciplines, :through => :equivalences,:source => :discipline
end

app/models/subject_course.rb
class SubjectCourse < ApplicationRecord
  belongs_to :subject
  belongs_to :course
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
  belongs_to :user
  has_many :classrooms

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_one :teacher
    mount_uploader :avatar, AvatarUploader
    enum kind: {
      standard: 2,
      admin: 1,
      coordenator: 3
    }
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    
    @teacher = Teacher.new
    @users = User.all
    @departments = Department.all
  end

  # GET /teachers/1/edit
  def edit
    @users = User.all
    @departments = Department.all
  end

  # POST /teachers
  # POST /teachers.json
  def create
    
    
    @teacher=Teacher.new(teacher_params)
    @teacher.name=User.find_by(id: @teacher.user_id).name
    

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :registration, :age, :department_id, :user_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessions_helper.rb
module LessionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
   
end

app/helpers/users_helper.rb
module UsersHelper
    def user_kind_option
        [["padrao", :standard]]
    end

    def user_kind_option_with_admin
        [["padrao", :standard],["coordenador", :coordenator],["adimistrador", :admin]]
    end
    

end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= form.hidden_field :name %>
  </div>

  <div class="field">
    <%= form.label :registration %>
    <%= form.text_field :registration %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.select:department_id, @departments.collect { |department| [department.name, department.id] } %>
  </div>

  <div class="field">
    <%= form.label :user %>
    <%= form.select :user_id, @users.collect { |user| [user.email, user.id] }  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'ver mais sobre', @teacher %> |
<%= link_to  'voltar', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professor</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Registro</th>
      <th>Idade</th>
      <th>Departamentoo</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.registration %></td>
        <td><%= teacher.age %></td>
        <td><%= teacher.department.name %></td>
        <td><%= teacher.user.name %></td>
        <td><%= link_to 'ver mais sobre', teacher %></td>
        <% if can? :manager, Teacher%>
          <td><%= link_to 'Editar', edit_teacher_path(teacher) %></td>
          <td><%= link_to 'excluir', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :manager, Teacher%>
  <%= link_to 'Novo Professor', new_teacher_path %>
<% end %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to  'voltar', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Registro:</strong>
  <%= @teacher.registration %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @teacher.age %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @teacher.department.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @teacher.user.name %>
</p>
<h3>Turmas</h3>
<% for classroom in @teacher.classrooms%>
  <%=classroom.registration%>

<% end %>
<% if can? :manager, @teacher%>
  <%= link_to 'Editar', edit_teacher_path(@teacher) %> |
<% end %>
<%= link_to  'voltar', teachers_path %>